Repository precog/tectonic, pull requests merged in 2018-10, with the labels that each got.

#7 Added DelegatingPlate
  core/src/main/scala/tectonic/DelegatingPlate.scala
Labels: version: feature

#8 Added the ability to visit a reified event stream
  test/src/main/scala/tectonic/test/ReifiedTerminalPlate.scala
Labels: version: feature

#10 Remove Plate#enclosure() and track all state internally
  core/src/main/scala/tectonic/DelegatingPlate.scala
  core/src/main/scala/tectonic/Plate.scala
  core/src/main/scala/tectonic/json/AsyncParser.scala
  core/src/main/scala/tectonic/json/Parser.scala
  core/src/main/scala/tectonic/util/BList.scala
  test/src/main/scala/tectonic/test/ReifiedTerminalPlate.scala
  test/src/test/scala/tectonic/json/AsyncParserSpecs.scala
Labels: version: breaking

#13 Auto-bump in slamdata/qdata
  scripts/tectonicPublishAndTag
Labels: version: revision

#15 Do the maven sync thing
  build.sbt
Labels: version: revision

#17 Cribbed parseLong infrastructure from Jawn
  core/src/main/scala/tectonic/util/InvalidLong.scala
  core/src/main/scala/tectonic/util/package.scala
Labels: version: feature

#18 Revert "Revert "Do the maven sync thing""
  build.sbt
Labels: version: revision

#19 Refactor StreamParser to allow for more efficient coalescing
  benchmarks/src/main/scala/tectonic/BlackholePlate.scala
  benchmarks/src/main/scala/tectonic/json/ParserBenchmarks.scala
  fs2/src/main/scala/tectonic/fs2/StreamParser.scala
  fs2/src/test/scala/tectonic/fs2/StreamParserSpecs.scala
Labels: version: breaking
